{% set name = "faker_elasticsearch" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f73de30342e1dd6bb5080c4dea0693ad941e62fae001a2068244a0e0929bd714

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

#test:
#  imports:
#    - faker_elasticsearch

about:
  home: "https://github.com/akashzcoder/faker_elasticsearch"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Fake data creation for elasticsearch database."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - akashzcoder
