package:
  name: faker_elasticsearch
  version: "1.0.0"

source:
  path: .

build:
  script:
    - python setup.py install

requirements:
  host:
    - tornado

test:
  imports:
    - faker_elasticsearch

about:
  license: MIT

extra:
  recipe-maintainers:
    - akashzcoder
